language: scala
sudo: required
dist: trusty

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.10.6
      jdk: openjdk7
      env: SCALAJS_VERSION="0.6.19"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJVM/test utestJS/test

    - scala: 2.11.11
      before_script:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/bin/travis_setup.sh | bash -x
      sudo: required
      env: SCALAJS_VERSION="0.6.19"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJVM/test utestJS/test utestNative/test

    - scala: 2.12.2
      env: SCALAJS_VERSION="0.6.19"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJVM/test utestJS/test

    - scala: 2.13.0-M1
      env: SCALAJS_VERSION="0.6.19"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJVM/test utestJS/test

    - scala: 2.10.6
      jdk: openjdk7
      env: SCALAJS_VERSION="1.0.0-M1"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJS/test

    - scala: 2.11.11
      env: SCALAJS_VERSION="1.0.0-M1"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJS/test

    - scala: 2.12.2
      env: SCALAJS_VERSION="1.0.0-M1"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJS/test

    - scala: 2.13.0-M1
      env: SCALAJS_VERSION="1.0.0-M1"
      script: sbt ++$TRAVIS_SCALA_VERSION utestJS/test

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
